spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  profiles:
    active: dev
    include: secret
  threads:
    virtual:
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    com.ll.sb231130: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: Medium
    baseUrl: "http://localhost:${server.port}"
springdoc:
  swagger-ui:
    path: /swagger-ui.html

